### ISSUE TITLE
No protocol specified    [VGL] ERROR: Could not open display :0.

### ISSUE THREAD

**Issue by moorage** [willkessler/nvidia-docker-novnc#3]
I'm unable to run `gazebo` and `rosrun rviz rviz` from Terminator because of a display error.

```
root@2a24d5d302e1:~/my_project/catkin_ws# gazebo
No protocol specified
[VGL] ERROR: Could not open display :0.
No protocol specified
[VGL] ERROR: Could not open display :0.
```

```
root@2a24d5d302e1:~/my_project/catkin_ws# rosrun rviz rviz
No protocol specified
[VGL] ERROR: Could not open display :0.
```

**Comment by willkessler** [comment]
When you set up the host, make sure you allocate at least 50Gb disk space and at least one GPU.

![image](https://user-images.githubusercontent.com/176268/38177239-00283584-35b3-11e8-9c84-4f788120caca.png)

![image](https://user-images.githubusercontent.com/176268/38177244-0b6b4d3c-35b3-11e8-8605-ed184afa59a6.png)

**Comment by willkessler** [comment]
Note that in the above, I chose zone `us-east-1c` which seems to have GPU's most reliably these days.

**Comment by moorage** [comment]
I figured out my issue; the CUDA startup script was causing problems.  When I created the instance like the following, it worked!!

```
gcloud compute instances create gpu-gazebo \
    --machine-type n1-standard-8 --zone us-central1-c \
    --accelerator type=nvidia-tesla-k80,count=1 \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE --restart-on-failure \
    --boot-disk-size 30GB \
    --tags novnc-40001
```

**Comment by willkessler** [comment]
Makes sense... and you'll have more GPUs available in us-east-1c zone.

I only spun hosts up with the GC Console GUI, so didn't encounter the issue you faced.

**Comment by trn84** [comment]
Hi,

I have two servers with the same configuration. On one everything works fine and on the other I get the same error as above. Are you sure this has anything to do with the number of GPUs?

BR

**Comment by willkessler** [comment]
I'm not 100% sure, as I've seen this now when I've installed other x-windows configs besides the one in this repo. When you say "the same configuration", are you saying the hosts are identical including all the steps in this repo and you still get the error? I wonder if something happened during the building of the hosts e.g. one of the repo's they depend on changed. Are you able to repro?

**Comment by trn84** [comment]
Hi Will,

thank you for your swift reply. Maybe the phrase "same configuration" was misleading. I meant it with regards to the HW-configuration. Please tell me if I understand this correctly. Is there a running X11 server + Displaymanager required on the host OS? I thought that since lubuntu-desktop is installed within the container there is no need for any X11/DM on the host? 

I could reproduce the repo on a dedicated server system but only if there is a proper configured Xorg process running (seen by nvidia-smi command).

BR

**Comment by harishanand95** [comment]
@willkessler @trn84  I'm facing a similar issue. Any updates?

**Comment by willkessler** [comment]
You are running the xserver on the host. You are tunneling GPU graphics through to it.  See:

https://github.com/willkessler/nvidia-docker-novnc/blob/master/setup_host/add_xhost.sh

See where it starts up `lightdm`. The graphics are being rendered on the host and just tunneled through to the container.

**Comment by harishanand95** [comment]
Thanks a lot,
I'm a bit confused here, so the graphics is rendered on the host machine's Lubuntu desktop DISPLAY:0 and shown in container using VNC-NoVNC setup?

**Comment by slessans** [comment]
@harishanand95 @willkessler i found that if you setup a host machine, it works fine. If you stop the instance and then start it again later you need to re-run the add_xhost script or you end up with the display error.

**Comment by willkessler** [comment]
That's a good tip @slessans . In our use case, student VMs are recycled and never restarted so we never hit this issue. In addition, certainly if you don't need ROS, don't build with it. One of our primary users is our Robotics course which uses it heavily.

**Comment by willkessler** [comment]
> Thanks a lot,
> I'm a bit confused here, so the graphics is rendered on the host machine's Lubuntu desktop DISPLAY:0 and shown in container using VNC-NoVNC setup?

[TurboVNC docs](https://turbovnc.org/About/Introduction) might help explain the tunneling aspect.

**Comment by trn84** [comment]
Hi guys,

One more thing which is mostly a X11 question. Everything works fine when I have a display attached to the host. However, on the headless servers there is no graphics support available in the container since there is no display (hence no :0). Is there a way to avoid this? Right now I have to attach a display once to the system which is quit annoying.

I guess there is a solution since your example was running on the google cloud?!

**Comment by willkessler** [comment]
Yes, this solution has always been running on google cloud.

We use `DISPLAY=:1` to run apps on the lubuntu desktop. Note that you must run VGL apps from the linux desktop due to the vglrun alias (see https://github.com/willkessler/nvidia-docker-novnc/blob/82957c34398226e916023467b6faae4d37f6fd54/autonomous_sys_build/Dockerfile#L86)

Otherwise you'll get errors like so
```
root@ae998fac0a9a:/home/workspace# glxgears 
Xlib:  extension "GLX" missing on display ":1".
Error: couldn't get an RGB, Double-buffered visual
```

**Comment by trn84** [comment]
Dear Will,

thx for the reply. In fact I have the terminator settings like you have suggested. However, there is no DISPLAY=:1 if I am running headless on a server. I have tried the following guide:

https://carla.readthedocs.io/en/latest/carla_headless/

It seems to work natively on the server (although seg fault at the end of glxinfo) but it is not working from inside the docker container. Any further ideas?

**Comment by willkessler** [comment]
I believe these two lines are relevant (possibly not the first but definitely the second):

https://github.com/willkessler/nvidia-docker-novnc/blob/82957c34398226e916023467b6faae4d37f6fd54/autonomous_sys_build/Dockerfile#L73

https://github.com/willkessler/nvidia-docker-novnc/blob/82957c34398226e916023467b6faae4d37f6fd54/run.sh#L3

In the second line we are injecting the `DISPLAY` env var into the container... is that what you're needing?
